# Generated by Django 5.2 on 2025-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_access',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
