# Generated by Django 5.2 on 2025-07-18 06:08

import checker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_remove_customuser_has_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=checker.models.payment_screenshot_path),
        ),
    ]
